export { OylLogo } from './oyl'
export { LeatherLogo } from './leather'
export { PhantomLogo } from './phantom'
export { XverseLogo } from './xverse'
export { UnisatLogo } from './unisat'
export { WizzLogo } from './wizz'
export { OkxLogo } from './okx'
export { MagicEdenLogo } from './magiceden'
export { default as OrangeLogo } from './orange'
export { LaserEyesLogo } from './lasereyes-logo'
export { TokeoLogo } from './tokeo'

export { WalletIcon } from './walletIcon'
